---
- name: Verifica a existência do arquivo no destino {{ item.dest }}
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  register: file_exist

- name: Cria Backup do arquivo de configuração {{ item.dest }}
  ansible.builtin.copy:
    src: "{{ item.dest }}"
    dest: "/tmp/{{ item.name }}"
    backup: true
    remote_src: true
  when: (file_exist.stat.isreg is defined) and (file_exist.stat.isreg)


