---
- name: Adiciona repositório no CentOS
  ansible.builtin.get_url:
    url: "{{ url.centos }}"
    dest: "{{ repository.dest }}"
    mode: "{{ repository.mode }}"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Adiciona repositório no RedHat
  ansible.builtin.get_url:
    url: "{{ url.rhel }}"
    dest: "{{ repository.dest }}"
    mode: "{{ repository.mode }}"
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Instala a versão mais recente do Rsyslog
  ansible.builtin.yum:
    name: "{{ package }}"
    state: latest
    update_cache: true
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: Cria Backups dos Arquivos
  ansible.builtin.include_tasks: "backup_each.yml"
  loop: "{{ rsyslog_config }}"
  loop_control:
    loop_var: item

- name: "Realiza a Configuração do Rsyslog"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ rsyslog_config }}"

- name: Checa se as configurações estão funcionando
  block:
    - name: Checa se as configurações estão funcionando
      ansible.builtin.command: rsyslogd -N1
      register: rsyslog_reload
      changed_when: rsyslog_reload.rc != 0
  rescue:
    - name: Volta com a configuração anterior
      ansible.builtin.copy:
        src: "/tmp/{{ item.name }}"
        dest: "{{ item.dest }}"
        remote_src: true
      loop: "{{ rsyslog_config }}"

- name: Recarrega o rsyslog
  ansible.builtin.systemd:
    name: "{{ package }}"
    state: restarted
